### ISSUE TITLE
Persian translation on president.ir not working

### ISSUE THREAD

**Issue by marcel263** [mozilla/firefox-translations#513] opened 2022-09-19 15:45 UTC
**Describe the bug**
does not translate

**To Reproduce**
1. Go to president.ir/fa/
2. Click on 'Translate'
3. Notice how nothing gets translated, elements pending is 0
 
**Desktop (please complete the following information as possible):**
- Firefox Browser version: nightly 2022-09-19
- OS version: Linux 
- System type (32-bit or 64-bit):
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: president.ir
- Language of the webpage: Farsi
- Translating to (language): English
- Console logs from Web Developer Tools: no errors (loadLanguageModel function complete)

**Comment by sylvestre** [comment] 2022-10-12 14:41
I can reproduce this issue too.

**Comment by andrenatal** [comment] 2022-12-03 05:09
This was fixed on 1.2.0. Can't reproduce it anymore.

**Closed by andrenatal** 2022-12-03 05:09 UTC
Labels: bug
