### ISSUE TITLE
Firefox Automatic Translation screws with window spacing

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/firefox-translations#380] opened 2022-06-05 19:34 UTC
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:100.0) Gecko/20100101 Firefox/100.0

Steps to reproduce:

    Install Firefox Automatic Translation

    Visit https://archive.org/stream/sim_krasnyi-arkhiv_1926_19/sim_krasnyi-arkhiv_1926_19_djvu.txt

    Enable Firefox Automatic Translation

Actual results:

The left 80% of the window now occupies 100%. The right 20% is gone. The Firefox Automatic Translation toolbar includes "Parti" and is cut off halfway through the next letter.

Expected results:

Firefox Automatic Translation shouldn't affect window spacing...?

**Comment by riveravaldez** [comment] 2022-06-08 04:29
Just in case it's useful to know, I'm having the same issue in an Arch Linux box with updated Firefox from repositories.
Let me know if there's any info I could add that could be helpful.
Thanks a lot!

**Comment by andrenatal** [comment] 2022-06-28 03:00
Duplicate of https://github.com/mozilla/firefox-translations/issues/245
It will be addressed there. Thanks for reporting @riveravaldez!

**Closed by andrenatal** 2022-06-28 03:00 UTC
Labels: bug, UI/UX
