### ISSUE TITLE
show alternative translations

### ISSUE THREAD

**Issue by lhpitn** [mozilla/firefox-translations#695] opened 2023-03-22 13:51 UTC
### Is your feature request related to a problem? Please describe.

it would be nice if you would provide differtent possible translations when clicking on an translated sentence like then showing a list whith different translations and what they mean in original language, like what other translation service provide

### Describe the solution you'd like

see above

**Comment by marco-c** [comment] 2023-07-11 12:17
Duplicate of #382.

**Closed by marco-c** 2023-07-11 12:17 UTC
Labels: duplicate, enhancement, UI/UX
