### ISSUE TITLE
[Linux] Firefox header cut off when translations enabled

### ISSUE THREAD

**Issue by arnaudvergnet** [mozilla/firefox-translations#356] opened 2022-06-02 17:39 UTC
When enabling translations on my Ubuntu machine, the Firefox header is way too wide and cut off from the window. No matter how I resize the window, the header size does not change. I need to make the window about 2200 pixels wide for content not to be cut off anymore.

Only the Firefox header is cut off, the page's content is fine. Only the tab with translations enabled is affected. If I refresh the tab, the header goes back to normal.

| Normal | With translations enabled |
|-|-|
| ![Screenshot_20220602_192957](https://user-images.githubusercontent.com/80701113/171689357-86347565-fedc-4577-a532-6c253d86c38f.png) | ![Screenshot_20220602_193005](https://user-images.githubusercontent.com/80701113/171689371-63aedd6f-9fcf-4dea-95d8-6b1621cd0242.png) |

System information:
- OS: Ubuntu 20.04 LTS
- Firefox: 100.0.2
- Firefox Translations: 1.1.2buildid20220523.151256

**Comment by riveravaldez** [comment] 2022-06-08 04:32
> Probably related to (or the same issue as?) #245

Seems like, even more #380

**Comment by bjherbison** [comment] 2022-06-24 11:26
Not only are the Firefox controls cut off, but the Window controls are cut off. Notice that in the right image in .0 the close, maximize, and minimize buttons are missing. As with .0 I also have tabs in the title bar and sometimes the current tab isn't shown in the title bar because it gets pushed off the right side of the window.

I'm disabling the add-on until this gets fixed. It's too frustrating to keep losing my window controls and tabs.

System information:

- OS: Ubuntu 20.04 LTS (Same as .0)
- Window Manager: XFCE
- Firefox: 103.0a1 (Nightly) with tabs in title bar
- Firefox Translations: 1.1.2buildid20220523.151256 (same as .0)

**Comment by andrenatal** [comment] 2022-06-28 03:08
This is a duplicate of https://github.com/mozilla/firefox-translations/issues/245 like noted above, let's move the discussion there. Thanks everyone for reporting!

**Closed by andrenatal** 2022-06-28 03:08 UTC
Labels: bug, UI/UX
