### ISSUE TITLE
"Translation preferences" doesn't really seem to go anywhere

### ISSUE THREAD

**Issue by Vinnl** [mozilla/firefox-translations#325] opened 2022-05-09 09:20 UTC
When I click "Translation preferences", I just get sent to the general Firefox preferences. Not sure if there should be anything specific to translations there?

https://user-images.githubusercontent.com/4251/167380055-8c92ea2a-d7a5-4e94-84d2-d5f3ac445fce.mp4

This is on Fedora Workstation 35, Firefox 100.

Edit: ah, in the Foxfooding doc I see that there are new options under "Language" (in the "Language and Appearance" section). Maybe it should at least scroll down there, possibly with an additional focus indicator?

**Comment by cadeyrn** [comment] 2022-05-09 09:50
Duplicate of #319.

**Closed** 2022-05-09 09:57 UTC
