### ISSUE TITLE
Text field of free translation form should not be cleared when panel gets closed

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/firefox-translations#588] opened 2022-11-26 14:41 UTC
After entering something in the free translation form and closing the panel (for example because you click outside to read or copy something from a website) the text field is empty again and you have to re-enter everything you wanted to translate. This can be a very frustrating user experience. I suggest not to clear the text field when the panel gets closed.

**Comment by andrenatal** [comment] 2022-12-03 04:17
dupe of #584

**Closed by andrenatal** 2022-12-03 04:17 UTC
Labels: needs triage
