### ISSUE TITLE
Translation quality from Icelandic to English is not very good

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#164] opened 2022-03-16 11:22 UTC
Description:
Accessed several Icelandic websites and translated them (to English) and found that the translation quality is not very good.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access several sites in Icelandic (https://www.volkswagen.is/is.html and https://www.cocacolaep.com/is/mannauour-og-menning/ ,for example)
3. Translate the pages and observe the quality of the translation

Actual:
The translation quality from Icelandic to English is not very good.

Expected:
Pages like https://is.wikipedia.org/wiki/%C3%8Dsland are translated with great accuracy and quality.
Pages like the ones above should have the same level of accuracy and quality when translated.

For more details, see the attached screenshots. The screenshots depict just small portions of the translated pages.

![2022-03-16_13h05_30](https://user-images.githubusercontent.com/50236075/158579098-c501d8f8-a246-4c9c-b89f-cdb7c49170fd.png)

![2022-03-16_13h05_43](https://user-images.githubusercontent.com/50236075/158579129-5615540c-bfa7-4fe2-9af1-6c4ed8cc1ef7.png)

**Comment by kpu** [comment] 2022-03-16 12:43
Indeed this is not a strong model.  I indicated this to Mozilla and they settled on the "beta" label.  Worth considering product reputation impact.

**Comment by eu9ene** [comment] 2022-03-16 19:29
This is "by design". You can see [here](https://github.com/mozilla/firefox-translations-models/blob/main/evaluation/dev/results.md) that we have a bunch of language pairs in `dev` folder. Those are test models with bad quality. They were trained to test the pipeline. These pairs are marked as "Beta" in the extension and intended mostly to test support of different languages (detection, websites etc.)

If you suggest getting rid of those models even for testing, let's create another issue or propose another mechanism how to make this more explicitly for a user if marking with "Beta" is not enough.

**Closed by eu9ene** 2022-03-16 19:29 UTC
