### ISSUE TITLE
Make it available on Firefox Mobile

### ISSUE THREAD

**Issue by lonnen** [mozilla/firefox-translations#413] opened 2022-06-23 17:41 UTC
From Luca on the fx-translations@mozilla.com list:

```
Hello,

Please make it available to Firefox on mobile!

The Firefox apps needs a build-in translator app.

Many thanks!
```

We've looked at this a couple of times but didn't have it on file as an issue. Improved support for ARM processors is an underlying blocker to this that also impacts some laptops, but there's likely some specific work to getting the extension working on Firefox Mobile.

Filing this as a convenient place to watch for any future updates

**Comment by andrenatal** [comment] 2022-06-28 03:01
Duplicate of https://github.com/mozilla/firefox-translations/issues/374

**Closed by andrenatal** 2022-06-28 03:01 UTC
Labels: enhancement
