### ISSUE TITLE
Extension doesn't run in a clean Firefox Profile

### ISSUE THREAD

**Issue by abhi-agg** [mozilla/firefox-translations#129] opened 2022-02-28 13:47 UTC
Followed [preliminary-builds of README](https://github.com/mozilla/firefox-translations#preliminary-builds) instructions to install the extension in Firefox Nightly and opened non-English pages.

The infobar doesn't get invoked.

**Setup**:
Firefox Nightly (en-US) version: 99.0a1 (2022-02-28) (64-bit)

New profile created using [instructions](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_manage-profiles-when-firefox-is-open).

Extension installed from: https://github.com/mozilla/firefox-translations/actions/runs/1908018733

Status of prefs at `about:config` after installing the extension:
    - `extensions.translations.disabled` is `true`
    - `extensions.experiments.enabled` is `true` 
    - `javascript.options.wasm_simd_wormhole` is `true`
    - `xpinstall.signatures.required` is `false`

Tested on pages: `https://www.bbc.com/mundo` and `https://www.dw.com/de/themen/s-9077`

**Comment by abhi-agg** [comment] 2022-02-28 13:50
@andrenatal @eu9ene Could any one of you please try to reproduce it? I believe this issue and https://github.com/mozilla/firefox-translations/issues/128 are connected.

**Comment by andrenatal** [comment] 2022-03-03 08:35
Yes, I could reproduce this issue and the cause is a conflict with the legacy in-tree extension. The workaround is to restart the browser after the installation, which I added to the new setup steps that I just pushed.

After we remove the legacy system addon, this won't happen anymore, as also with the signed one. Will keep this open so we can track when that happens, but will move to the next milestone since it won't happen before the holidays.

**Comment by andrenatal** [comment] 2022-03-03 09:13
Actually the root cause here is a different thing: since we utilize the privileged experiments API, the browser needs to be restarted so those permissions could be loaded during startup, so this is by design and there's no way for us to change that behavior in the addon. Will close it.

**Closed by andrenatal** 2022-03-03 09:13 UTC
