### ISSUE TITLE
"We found an error loading the translation engine" leaves extention permanently broken.

### ISSUE THREAD

**Issue by Miserlou** [mozilla/firefox-translations#361] opened 2022-06-02 18:09 UTC
FF 101.0, OSX 10.15

Was happily using the extention, trying a few different sites and languages out, and now it is a permanently broken state. Any translating immediately gives "We found an error loading the translation engine." This happens on pages which worked 15 minutes ago. There is no indication what the error is. Restarting Firefox does not help.

Since getting the error, I downloaded a different language, which did work. My first language (Norsk Bokmal) is still broken.

**Comment by Miserlou** [comment] 2022-06-02 18:11
Another user is getting this: https://news.ycombinator.com/item?id=31598456 - maybe being #1 on HackerNews is a problem?

However, I previously downloaded and used the model just fine. I was expecting the extention not to make any network calls, so if a downed remote service is causing the local model not to work, I'm a bit disappointed.

**Comment by kpu** [comment] 2022-06-02 21:37
As an aside, the Norsk Bokmal model is more alpha quality than the other languages.

**Comment by ellotheth** [comment] 2022-06-03 07:09
Same behavior on Firefox 102.b3, Ubuntu 20.04.4, Norsk Bokmål. Uninstalling, restarting the browser, reinstalling, and restarting fixed it for me.

**Comment by andrenatal** [comment] 2022-06-07 18:26
Hi @Miserlou @ellotheth would you mind sharing the sites that put your extension on this state so I could try to reproduce, please?

**Comment by ellotheth** [comment] 2022-06-08 05:09
@andrenatal I think I was testing it on https://helsenorge.no, but I haven't been able to reproduce it since I reinstalled (apologies 😅).

**Comment by andrenatal** [comment] 2022-06-13 21:12
Thanks @ellotheth . And about you @Miserlou ? Are you still seeing this?

**Comment by andrenatal** [comment] 2022-06-23 21:36
I'll close this due lack of input, but if this behavior shows up again, please just reopen it.

**Closed by andrenatal** 2022-06-23 21:36 UTC
Labels: bug, needinfo
