### ISSUE TITLE
Add translation web page to addon

### ISSUE THREAD

**Issue by joveian** [mozilla/firefox-translations#381] opened 2022-06-06 01:50 UTC
Currently there is a [web page version](https://mozilla.github.io/translate/) of the translator but it doesn't seem to be part of the addon, although it would be helpful.  It would be particularly helpful if this page could be registered as a search engine (or, I guess, as several search enginges per language pair) so that it could be used with the [right click search](https://addons.mozilla.org/en-US/firefox/addon/right-click-search/) addon to translate text (I am currently doing exactly this with Google Translate and it works well, although I use the convenient autodetect source language that would also be a handy feature if possible).  Or, maybe better, there could be a special right click menu option just for translation that does the same thing and where the language pairs to show (and ideally the order to show them as well) could be configured in the addon settings.

This could be one way to implement #358.

**Comment by kpu** [comment] 2022-06-06 09:32
The extension could definitely use an about: or config page that just translates plain text.  

Check out https://translatelocally.com/ that may meet your use case more directly.

**Comment by andrenatal** [comment] 2022-11-02 01:01
dupe of #479

**Closed by andrenatal** 2022-11-02 01:01 UTC
Labels: enhancement
