### ISSUE TITLE
non-HTML input is treated as HTML

### ISSUE THREAD

**Issue by jelmervdl** [mozilla/firefox-translations#51] opened 2022-01-26 13:09 UTC
It looks like [all input is marked as HTML for the translator](https://github.com/mozilla/firefox-translations/blob/c21b61fdd1dc3186bb478c7702d601dc20b7b336/extension/controller/translation/translationWorker.js#L496
), even though [nodes' text content is submitted](https://github.com/mozilla/firefox-translations/blob/c21b61fdd1dc3186bb478c7702d601dc20b7b336/extension/view/js/InPageTranslation.js#L135-L158). If a node contains something like `<p>Hello &lt; world</p>`, it would submit `Hello < world`. Which when parsed as HTML is invalid input and would cause an exception.

Even if HTML was being submitted, it would not be properly used (and cause an `abort()`) because the model doesn't produce alignment information. In [the model configuration yaml](https://github.com/mozilla/firefox-translations/blob/c21b61fdd1dc3186bb478c7702d601dc20b7b336/extension/controller/translation/translationWorker.js#L262-L275), the line `alignment: soft` is missing.

**Comment by andrenatal** [comment] 2022-01-26 19:18
@jelmervdl Maybe this is related to https://github.com/mozilla/firefox-translations/issues/35, where I'm seeing multiple exceptions in the engine but can't reproduce on different languages?

**Comment by jelmervdl** [comment] 2022-01-26 20:56
@andrenatal it could be very well related. There are paragraphs with literal `<` and `>` in them. Those paragraphs would cause the html parsing bit in bergamot-translator to throw (but because of how emscripten is configured… abort()?) since it tries to parse that as an open tag and fail.

**Comment by kpu** [comment] 2022-01-26 21:19
The extension will be called upon to translate `text/plain` and `text/HTML` documents, so the extension will need to toggle HTML on/off anyway, using this:

https://github.com/browsermt/bergamot-translator/blob/c0f311a8c067372057a6f301c42b40bbe30a9c1a/src/translator/response_options.h#L22
(The TODO comment is outdated and will be fixed.)

**Comment by andrenatal** [comment] 2022-01-27 08:54
@abhi-agg could you please take a look at this?

**Comment by abhi-agg** [comment] 2022-01-27 18:11
@andrenatal I am on it.

**Comment by abhi-agg** [comment] 2022-01-27 18:18
> The extension will be called upon to translate `text/plain` and `text/HTML` documents, so the extension will need to toggle HTML on/off anyway

@kpu By `documents`, do you literally mean the user will upload documents to translate or do you only mean web pages?

**Comment by kpu** [comment] 2022-01-27 18:57
The user could browse to a web page with a text/plain content type.  The browser displays the text, which may include stray < and > that should not be interpreted as HTML.

**Comment by kpu** [comment] 2022-01-27 19:02
As in, a user with a German Firefox UI visits https://neural.mt/test.txt .  The browser offers to translate it to German.  The text should be sent to the engine with HTML off.

**Comment by abhi-agg** [comment] 2022-01-27 19:59
Did some quick tests via wasm test page:
1. Assuming right model config was set and response options are set to do html translation
    1. `Hello &lt; world.` returned following for various models:
        1. De: `Hallo Welt.`
        2. Es: `Hola, mundo.`
        3. Cz: `Ahoj, svět.`
        4. Et: `Tere &lt; maailm.`
        (Seems like `&lt;` is gone in De, Es and Cz language)
    2.  `Hello < world` causes engine to assert (because given string is a bad-formed html)
1. Non-html translation for `Hello &lt; world. Hello < world.` returned follwing:
    1.  De: `Hello &lt; Welt. Hallo Welt.`
    2. Es: `Hola &lt; mundo. Hola, mundo.`
    3. Cz: `Hello &lt; world. Ahoj, svět.`
    4. Et: `Tere &lt; maailm. Tere < maailm.`

**Comment by kpu** [comment] 2022-01-27 20:16
That looks consistent with expectations.  The HTML mode is mapping `Hello &lt; world.` to text `Hello < world.` internally which is then translated to Czech as `Ahoj, svět.` or Estonian as `Tere < maailm.` as internal text.  Which is then unescaped to `Tere &lt; maailm.`

**Comment by andrenatal** [comment] 2022-01-29 11:20
Wasn't this fixed by: https://github.com/mozilla/firefox-translations/pull/53? 

Can we close it?

**Comment by kpu** [comment] 2022-01-29 13:26
There's a few things going on:
1. `alignment: soft` was not passed at load time so HTML didn't know what to do with word alignments, resulting in poor HTML placement quality.  This was mentioned as part of the initial issue and is now resolved as #53.
2. The extension is currently extracting text and sending it to the engine with HTML on.  This means a stray `&lt;` in the HTML is converted by the extension to `<` which then confuses HTML mode in the engine.  This was also mentioned as part of the issue and remains open to my knowledge.  We believe this is the cause of the crash in #35.  
3. The extension has no means to toggle the HTML flag.  This will be required at some point since users may browse to `text/plain` and `text/html` pages.  I have suggested doing this as part of the fix of point 2 above.  
4. The extension should use HTML mode instead of sending text, which is #52.

**Comment by andrenatal** [comment] 2022-01-29 18:34
What happens in the case of a legit instance of `< ` existent in the page's text being sent to the engine?

**Comment by kpu** [comment] 2022-01-29 18:46
If you have HTML mode on and provide ill-formed HTML, it will throw an informative exception to the request and the engine will be fine (to take more requests).  However, the `-fno-exceptions` maps limitation of WASM maps this exception to process death.  In Thursday's plenary, I raised the possibility of an API change to allow returning an error code, as the current API does not have the means to express errors by anything other than exceptions.  See https://github.com/browsermt/bergamot-translator/issues/316 .  

HTML mode was originally scoped to be used with Firefox's innerHTML where it's not possible to pass erroneous HTML.  

We could of course improvise something to just skip the character or treat it as if it were `&lt;` but this seemed like it would only cause trouble of being inconsistent with Firefox's interpretation of broken HTML.

**Comment by jelmervdl** [comment] 2022-01-29 21:27
Note that you can specify whether to use HTML mode every time you call `translate()`. For translating `innerHTML` it should be on, but for translating `textContent` or the outbound form inputs it should not be on.

Right now the extension does some batching, calling `translate()` with a `VectorString` with multiple input strings, but only one `ResponseOptions` object which specifies whether they are all HTML or not. I.e.

```js
const responseOptions = {qualityScores: true, alignment: true, html: true};
let input = new this.WasmEngineModule.VectorString();
messages.forEach(message => {
    input.push_back(message.sourceParagraph);
});
let result = this.translationService.translate(translationModel, input, responseOptions);
```

 We can alter the emscripten bindings of bergamot-translator a bit and accept a ResponseOptions object per input string, if that makes the extension's code easier. Something like:

```js
const responseOptions = {qualityScores: true, alignment: true};
let input = new this.WasmEngineModule.VectorSomethingSomething();
messages.forEach(message => {
    input.push_back(message.sourceParagraph, {...responseOptions, html: message.isHTML});
});
let result = this.translationService.translate(translationModel, input);
```

**Comment by andrenatal** [comment] 2022-01-31 22:20
Based on my conversation with Abhi, we'll need the InPageTranslation.js parser to always determine if the string being passed to the engine contains plain or html text and set the proper flag on ResponseOptions. Is that right @abhi-agg ?

**Comment by andrenatal** [comment] 2022-02-01 16:07
If the above is the case, it demonstrates a weakness of the engine itself: it shouldn't be the presentation layer responsibility to determine the type of the content being input, the user should just be able to input whatever they and and the engine itself infer that. There will be use cases where this won't be possible, like SOA applications for example. Unfortunately this is a bad design decision that can lead to even more issues

**Comment by kpu** [comment] 2022-02-01 16:42
All you need to do to fix this issue for the time being is turn the HTML flag to off.  This is a one line change.  When you have HTML translation again, turn it on.  

The HTML feature is designed to operate on snippets of HTML.  It does not make sense to expect automatic content identification from text vs snippets of HTML because that would introduce bugs in text translation where words are mysteriously not translated inside angle brackets.  

Does Firefox render text/plain content containing some tags as HTML?

**Comment by abhi-agg** [comment] 2022-02-01 17:00
> All you need to do to fix this issue for the time being is turn the HTML flag to off. This is a one line change. When you have HTML translation again, turn it on.

Submitted the PR that should close this issue.

> If the above is the case, it demonstrates a weakness of the engine itself: it shouldn't be the presentation layer responsibility to determine the type of the content being input, the user should just be able to input whatever they and and the engine itself infer that. There will be use cases where this won't be possible, like SOA applications for example. Unfortunately this is a bad design decision that can lead to even more issues

This leaves ⬆️  up for discussion.

**Comment by kpu** [comment] 2022-02-01 17:49
Thanks @abhi-agg!

**Closed** 2022-02-03 06:22 UTC
Labels: bug
