### ISSUE TITLE
We could not find the translation engine to download

### ISSUE THREAD

**Issue by Rahjooyan** [mozilla/firefox-translations#491] opened 2022-08-14 21:32 UTC
Hi, i tried some languages like English or italian or persian websites but i have this problem. i tried to translate them to another languages but it was useless. I have latest version of firefox. 

it shows translate toolbar but when i click to translate pages, it shows this error:
“We could not find the translation engine to download”

please help me to fix this.
Thanks.

**Comment by kpu** [comment] 2022-08-14 21:46
Duplicate of #487

**Comment by Rahjooyan** [comment] 2022-08-15 16:29
Hi.
1. I don't know how to use models manually. I downloaded all files from here:
`https://github.com/mozilla/firefox-translations-models/tree/main/models/dev/faen`
`https://github.com/mozilla/firefox-translations-models/tree/main/models/dev/enfa`

do I need to copy extracted files here?
`C:\Users\USERNAME\AppData\Local\Mozilla\Firefox\Profiles\1ok9dd0q.default-release\cache2 `

I tried this but it didn't work.

2. Please add true fix for this problem. I need this feature for all languages not En/Fa languages only.
Thanks.

**Comment by kpu** [comment] 2022-08-15 18:55
Can you try https://github.com/jelmervdl/firefox-translations/releases/download/v0.6.1/bergamot_translations.xpi and tell me if that works for you?  

It also supports https://translatelocally.com/ as a native messaging backend.  In translatelocally the native application you can indeed add models on the side following directions on https://github.com/XapaJIaMnu/translateLocally .  But I think the above extension will Just Work for you.

**Comment by sylvestre** [comment] 2022-10-13 16:24
Dup & no activity, closing

**Closed by sylvestre** 2022-10-13 16:24 UTC
Labels: needs triage
