### ISSUE TITLE
Firefox Translations bar truncated on the right side

### ISSUE THREAD

**Issue by Kimpa-Tammas** [mozilla/firefox-translations#411] opened 2022-06-20 18:29 UTC
**Describe the bug**
My Firefox window is displayed on my second monitor with a resolution of 1,280 x 1,024 px. When I activate the extension from her icon, the right part of the Firefox header is truncated. Note that the Web page is not truncated (scroll bar remains visible).

I use a custom system font and I think that the text size cause this. Also, French language is more verbose. May be using the default Firefox font size could be better or move check-case options in the Options drop-down list. 

**To Reproduce**
1. Open a Firefox full window on a monitor with a resolution of 1,280 x 1,024 px or resize the window to this resolution
2. Open the Firefox Translations bar
3. See the right side of the bar, this one is truncated
4. If this one isn't truncated, try to use fonts with different kerning (part truncated must increase or decrease following the font)

**Expected behavior**
The bar do not be truncated.

**Screenshots**
[https://gyazo.com/e387a68692c89a13f756585396b8eb99](https://gyazo.com/e387a68692c89a13f756585396b8eb99)
[https://gyazo.com/a0ed48e052bdf631f1a380fb8ede712c](https://gyazo.com/a0ed48e052bdf631f1a380fb8ede712c)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 101.0.1
- Processor information: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
- OS version: Windows 10 20H2
- System type (32-bit or 64-bit): 64 bits
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: Any webpage
- Language of the webpage: French
- Translating to (language): None
- Console logs from Web Developer Tools: None

System architecture and extension information can be found as follows:
- architecture: x86-64
- cpu.extensions: [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES]

**Additional context**

**Comment by barklan** [comment] 2022-06-23 19:10
Observe the same issue, even though contents of the bar should fit. Arch Linux, KDE Plasma (Wayland session), Firefox 103.0a1 (2022-06-23) (64-bit), Extension version: 1.1.2buildid20220523.151256

![Screenshot_20220623_220305](https://user-images.githubusercontent.com/71007493/175378571-b16435c4-e09a-4002-9415-f7df89a9d7fa.png)

**Comment by andrenatal** [comment] 2022-06-28 03:06
Duplicate of https://github.com/mozilla/firefox-translations/issues/245
It will be addressed there. Thanks for reporting @[Kimpa-Tammas](https://github.com/Kimpa-Tammas) and @barklan

**Closed by andrenatal** 2022-06-28 03:06 UTC
Labels: needs triage
