### ISSUE TITLE
Translation info bar has min-width so right-hand buttons slide off-screen

### ISSUE THREAD

**Issue by pixelplumber** [mozilla/firefox-translations#377] opened 2022-06-04 02:57 UTC
The translation info bar appears to have some sort of minimum width so that when you shrink the browser window down below about 1470px wide the buttons on the right slide off-screen instead of shrinking the distance between the buttons and the translation info on the left.
**edit: this is in nightly 103a1**

**Comment by andrenatal** [comment] 2022-06-07 19:03
Thanks for reporting this @pixelplumber . This is a duplicate of #245 . We are aware of this issue and are working to find ways to fix it. Will close this in favor of that one.

**Closed by andrenatal** 2022-06-07 19:03 UTC
Labels: duplicate
