### ISSUE TITLE
Stil seeing a lot of regressions on pt-br

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#231] opened 2022-04-07 19:09 UTC
It's clear that there's a regression here. 

@eu9ene and I met to evaluate that and it seems that marian is being automatically updated in bergamot-translator, which is probably causing a lot of these newly introduced issues in pt-br and ru. We need to identify what's happening and probably use mozilla's bergamot-translator repo to freeze versions since we don't have control on what's being landed on browsermt's can break our project or not.  

Notice the screenshot below all these repeated `,` and the `(em inglês)` annotations (which means "in english") after non-translated sentences, which are all over. This is critical and needs to be investigated during the next week's task force on bergamot-translator @abhi-agg 

![Screen Shot 2022-04-07 at 11 57 26 AM](https://user-images.githubusercontent.com/973388/162278259-911e94c9-e976-4697-a9fa-60c17c28bf91.png)
<img width="1224" alt="Screen Shot 2022-04-07 at 12 08 44 PM" src="https://user-images.githubusercontent.com/973388/162278477-4bfe3a2b-68dc-4097-9423-b78f11457b94.png">

**Comment by eu9ene** [comment] 2022-04-07 19:18
I agree it's critical to investigate this because if there are issues in the engine, they will be extremely hard to catch.

I see continuous version bumping of 3rd_party components in bergamot-translator https://github.com/browsermt/bergamot-translator/pulls?q=is%3Apr+is%3Aclosed. This makes it less stable. I would rather suggest freezing and updating components altogether periodically followed by a QA pass. We're trying to limit this by using the Mozilla fork, but if we can't avoid it if need to land the latest improvements from the bergamot-translator.

We should start by comparing translations of the same page using different versions of the extension and bergamot-translator module making sure that en-pt model version is the same.

**Comment by jerinphilip** [comment] 2022-04-07 20:44
> Notice the screenshot below all these repeated , and the (em inglês) annotations (which means "in english") after non-translated sentences, which are all over. 

Neural MT systems do the repeated comma, the proper fix is harder. Is `pt-br` a prod model? We may be able to work around this (by means of repetition detection in the decoding code), but the change is not going to be pleasant from a software correctness perspective. (Side-story: A colleague just recently was trying to do natural language to SQL translation. The software had repeated trigram detection and constraint which prevented it from generating nested parenthesis > 3. The point being, such a fix for the comma could break something elsewhere).

`Em Ingles` looks legible enough to not be counted as a bug from a software development perspective. The fix is probably in the data or ML model space (and the issue arising from unfiltered data on named entities used in training). 

I believe we're missing Nightly updates as a source of regression from time to time - https://github.com/browsermt/marian-dev/issues/81 is unaddressed, and there's nothing much we can do about it. 

Marian is not automatically updated, commits get in after review in browsermt/marian-dev. I'm the one pressing the merge buttons on dependabot's PRs at bergamot-translator. Sometimes these include improvements upstreamed by clients like translateLocally which goes through bergamot-translator and makes sense to have them in main. There are tests on small and large samples of data for translation which address stability. Please feel free to add more. It's as simple as adding files and expected outputs for more complex corner cases similar to [bergamot.html/input.txt](https://github.com/browsermt/bergamot-translator-tests/blob/main/data/simple/bergamot.html/input.txt).

**Comment by eu9ene** [comment] 2022-04-07 21:01
I'm close to finalizing retraining of en->pt with all the latest improvements in the pipeline, but the problem here is not the model but that it looks like quality regressed without a model update. We should investigate this. If it's true, it is a software problem, not training. Ideally, software should produce deterministic results for the same model. If not exactly the same, at least with the same level of quality.

**Comment by andrenatal** [comment] 2022-04-07 21:20
It's the first time since this started that I see these indicators of the language that couldn't be translated `"(Em Ingles)"` in this case, to show up, and, adding arbitrarily stuff to the page, it's not good and not only to the UX perpective. The pt-br model that's being used is the same for a long time, and I noticed also differences in the translation itself. So if we can't guarantee stability and compatibility between our project and the models we train with what's coming from upstream, we should utilize our own fork instead of browsermt's. @abhi-agg and I will develop that further next week after the holidays.

**Comment by eu9ene** [comment] 2022-04-07 21:50
@andrenatal I tried some older versions of the extension and also https://github.com/mozilla/translate that uses pretty old version of the engine ("v0.3.1+c7b626d") and I see those issues you pointed out to. So I guess they always were there, but they are pretty rare that's why you didn't see them before.
<img width="1061" alt="Screen Shot 2022-04-07 at 2 49 50 PM" src="https://user-images.githubusercontent.com/2486505/162325682-136b80f5-ffde-4837-bbc6-6ab13982e6ba.png">
<img width="1082" alt="Screen Shot 2022-04-07 at 2 49 44 PM" src="https://user-images.githubusercontent.com/2486505/162325692-270c9149-4710-4503-b383-45cfe0aa2624.png">

**Comment by eu9ene** [comment] 2022-04-07 22:04
We expect some variations for sure, the question was whether it is some sudden drastic regression in quality or not. It seems it's not, it just fluctuates for different texts.

**Comment by eu9ene** [comment] 2022-04-07 22:17
Closing then. Let's reevaluate quality when a new en->pt model will be ready.

**Closed by eu9ene** 2022-04-07 22:17 UTC
Labels: bug
