### ISSUE TITLE
[BUG] Menu is not showing

### ISSUE THREAD

**Issue by Shituation** [mozilla/firefox-translations#530] opened 2022-10-25 15:16 UTC
![sshot-001](https://user-images.githubusercontent.com/43975882/197813347-62f11c36-06ac-47a7-9263-1c7842f66e98.png)

The menu there cannot be expanded (clicking on the arrow doesn't do anything)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.1 (64-bit)
- Processor information: amd 64bit
- OS version: 21H2
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: all

**Comment by Fanolian** [comment] 2022-10-25 18:09
Same as #525.

**Comment by andrenatal** [comment] 2022-11-01 21:23
can't reproduce but might have been fixed by #527 and others

**Closed by andrenatal** 2022-11-01 21:23 UTC
Labels: needs triage
