### ISSUE TITLE
Ability to choose destination language to translate to

### ISSUE THREAD

**Issue by notDavid** [mozilla/firefox-translations#504] opened 2022-08-29 06:26 UTC
**Is your feature request related to a problem? Please describe.**
1. My operating system language is set to English (macOS)
2. My Firefox language is set to English. My secondary Firefox language is set to **Dutch**.

3. I go to a (random) German article: https://www.tagesschau.de/wirtschaft/finanzen/energiepreisdeckel-101.html
4. It says "This page is in German" and i click Translate
5. The text is now translated to English.

There seems to be no way to translate this page to **Dutch**, which is what i want.

**Describe the solution you'd like**
Ability to **choose** Dutch (or any other language) as the **destination language** to translate to.

**Comment by cadeyrn** [comment] 2022-08-29 06:50
Duplicate of #357.

**Closed as not planned** 2022-08-29 07:20 UTC
Labels: needs triage
