### ISSUE TITLE
Banner from clicking URL bar icon does not include all features

### ISSUE THREAD

**Issue by Fanolian** [mozilla/firefox-translations#567] opened 2022-11-12 05:54 UTC
**Describe the bug**
Some functions are missing on the translation banner if it is triggered by clicking the translation icon in URL bar. Users cannot re-enable translating a particular language easily from the banner (more on this in additional context).

**To Reproduce**
1. Install Firefox Translations 1.2 or nightly(7c7f4fc) on a new profile in Nightly (Currently 2022-11-11). Make necessary `about:config` changes.
2. Go to a site that auto-triggers translation banner, e.g. https://es.wikipedia.org/wiki/Wikipedia:Portada
3. Check the buttons on the banner.
4. Close the banner with the X button.
5. Open the banner by clicking the translation icon inside URL bar.

**Actual behavior**
Banner from step 5 misses some functions, namely `Never translate [lang]` (unrelated to #556 and duplicates) and `Enable translations of forms` (this one is also missing in v1.14)

**Expected behavior**
Both banners should show the same functionality.

**Screenshots**
~auto pop-up~ -> auto triggered
![Firefox Translations banner 1 2](https://user-images.githubusercontent.com/771216/201458680-f552a27f-ec12-43a8-9912-740253e68f58.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly 2022-11-11 (20221111093717)
- Processor information: 	x86-64 [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES] 
- OS version: Windows 10 22H2
- System type (32-bit or 64-bit): 64bit
- Firefox Translation Extension version: 1.2 or nightly (7c7f4fc)
- Webpage on which issue was observed: https://es.wikipedia.org/wiki/Wikipedia:Portada
- Language of the webpage: Spanish
- Translating to (language): English
- Console logs from Web Developer Tools: None

**Additional context**
~`Never translate [lang]` from URL bar banner does not work properly *even before* 1.2 (not about #556). It add a new entry in the exception list even if it is the same language.~ Fixed in v1.2.

**Comment by andrenatal** [comment] 2022-11-15 22:10
Hi @Fanolian, yeah, I'm aware of that and I remember there was some limitations in place limiting it. I'll keep this open so it could be revisited in the next version.

**Comment by andrenatal** [comment] 2023-01-14 05:01
I've checked and this behavior is by design because the background script responsible for handling the request to open the bar doesn't have access to the tab, which makes sense, since the user can change tabs while the request is being processed, so adding a step read the page and perform language detection there would lead to inconsistencies. We are planning to have this fixed in an upcoming architectural overhaul.

**Closed by andrenatal** 2023-01-14 05:01 UTC
Labels: bug
