### ISSUE TITLE
Top bar and translation popup stretch too far from screen

### ISSUE THREAD

**Issue by notalexnot** [mozilla/firefox-translations#427] opened 2022-06-30 19:14 UTC
**Describe the bug**
Tab bar (top bar) and the translation popup stretch too far in the screen after translating. I don't know if this may be important, but I use Spanish (México).

**To Reproduce**
1. Enter a website in english
2. Translate to spanish
3. The UI acts weird and extends far away from the original size. 

**Expected behavior**
Addon translating webpage and nothing else.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/43765089/176756425-1f36de5b-555d-4cfd-bdbd-1851fba6e93c.png)
---
![imagen](https://user-images.githubusercontent.com/43765089/176757466-e56b9d79-7a61-49f0-841a-4273fba79b8c.png)

**Desktop:**
- Firefox Browser version: 102.0 64 bits
- Processor information: AMD A8-7410
- OS version: Windows 10 21H2
- System type: 64 bits
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: All webpages translated from English to Spanish
- Language of the webpage: English
- Translating to (language): Spanish
- Console logs from Web Developer Tools: (see screenshot two).

**Comment by js-everts** [comment] 2022-07-02 17:12
This is being tracked here: #245

**Comment by andrenatal** [comment] 2022-07-05 18:07
closed as duplicate of #245

**Closed as completed by andrenatal** 2022-07-05 18:07 UTC
Labels: needs triage
