### ISSUE TITLE
translate `title` attributes

### ISSUE THREAD

**Issue by yukulele** [mozilla/firefox-translations#708] opened 2023-04-20 10:04 UTC
### Describe the solution you'd like

`title` (and probably `alt`) attributes should be translated.

**Comment by cadeyrn** [comment] 2023-04-20 10:44
Duplicate of #501 and [BZ-1819205](https://bugzilla.mozilla.org/show_bug.cgi?id=1819205) for the native Firefox integration.

**Closed** 2023-04-20 10:59 UTC
Labels: needs triage

**Comment by yukulele** [comment] 2023-04-20 12:39
#501 is about `<title>` element, this is about `title` attribute

**Comment by cadeyrn** [comment] 2023-04-20 12:48
Sorry, you're right. At least BZ-1819205 is really about the title attribute.
