### ISSUE TITLE
Firefox Translations bar is out of bounds in recent release

### ISSUE THREAD

**Issue by 0xC316c** [mozilla/firefox-translations#254] opened 2022-04-13 07:49 UTC
**Before**
![image](https://user-images.githubusercontent.com/82213558/163124161-2cc9c6b9-07b9-4032-b8fb-540e0b2bddf9.png)

**After**
![image](https://user-images.githubusercontent.com/82213558/163125680-0d219de2-475b-4302-be2c-4d71b33a085b.png)

So, the issue is translations bar is out of bounds and whatever above it (Menu Bar). Not sure about the Survey button being missing before using the translate button!

**P.S:** I am using Firefox Developer Edition

**Comment by andrenatal** [comment] 2022-04-13 15:46
Hello, thanks for testing and reporting! This is all intended behavior. 
- The survey button is supposed to be displayed only after the user actually uses the translation at least once;
- The counter of elements remains in zero to demonstrate that the engine is idle (if something is added to the DOM, that will automatically increase and decrease as it progress);
- And the issue with the bar is already being tracked here: https://github.com/mozilla/firefox-translations/issues/245

I'll close this to avoid duplicates, but please, keep reporting! 

Thanks

**Closed by andrenatal** 2022-04-13 15:46 UTC

**Comment by 0xC316c** [comment] 2022-04-13 18:31
Thank you very much but the second point you mentioned, I think it shouldn't show something is still pending to translate.

I think it's bad UX (User Experience) wise, but really doesn't matter much.

**Comment by andrenatal** [comment] 2022-04-13 21:09
I agree that UX was a deficient point in this project, so you could maybe file an issue just for that specific one and we take from there?
