### ISSUE TITLE
Form translation component should be always on top

### ISSUE THREAD

**Issue by michnov** [mozilla/firefox-translations#16] opened 2021-12-15 16:01 UTC
Even though the Outbound/Form translation component cannot be implemented as a native panel in the chrome (since it is not allowed for extensions to make use of XUL/XPCOM), it should act so and resemble it as much as possible. One of the expected features is that it always stays on top.

The following webpages show that in the implementation that I tested (https://github.com/mozilla/firefox-translations/actions/runs/1458463171), it is not always the case.

https://karriere.deutschebahn.com/karriere-de/jobs/Kontaktformular-4199212
![image](https://user-images.githubusercontent.com/11574860/146220022-cfd4398e-6b90-4b55-ab5c-23f39f45e00c.png)

https://www.tajmac-zps.cz/kontakte (then click on "Schreiben Sie uns/Write to us")
![image](https://user-images.githubusercontent.com/11574860/146220189-b59b3c53-3831-4f46-b6e8-a27bac67e806.png)

**Comment by michnov** [comment] 2021-12-15 16:12
Please let me know if there is an updated version of the extension that I should use.
My version of Nightly: 97.0a1

**Comment by andrenatal** [comment] 2022-01-23 09:24
Another case:


    Install current extension
    https://www.booking.com/hotel/gb/park-plaza-westminster-bridge.es.html
    Click translate
    Click Yes to enable translations of forms (and wait an unusually long time for "Loading form translation")
    Click "Ask a question." lower down in the page to open a modal dialogue.
    Click on the textarea.

**Comment by andrenatal** [comment] 2022-01-27 02:54
Closed in favor of https://github.com/mozilla/firefox-translations/issues/54

**Closed by andrenatal** 2022-01-27 02:54 UTC
Labels: bug, outbound-translation

**Comment by andrenatal** [comment] 2022-01-27 08:09
This was fixed by https://github.com/mozilla/firefox-translations/pull/55/commits/2602bad882a73c8674f8b881be3eab91e90892d0. I couldn't reproduce any of these behaviors with that patch.
