### ISSUE TITLE
BG locale infobar is not completely localized

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#150] opened 2022-03-10 10:42 UTC
Description:
When using a BG locale browser, the infobar is not completely localized in Bulgarian. For example:
- “Enable translations of forms” and “Enable quality estimation” checkbox descriptions are in English
- “Display statistics” option from the “Options” menu is in English
-  The messages displayed on the infobar after clicking the Translate button are in English. For example: the “Loading translation engine…”, “Automatic Translation enabled.”, etc are not localized in BG.

Pre-requisites:
1. Install a BG locale Nightly
2. Install the Firefox Translations extension

Steps to reproduce:
1. Access https://de.wikipedia.org/wiki/Wikipedia:Hauptseite, for example.
2. Notice the infobar is displayed and is partially localized in BG. However, the “Enable translations of forms” and “Enable quality estimation” checkbox descriptions are in English.
3. Click on the “Options” button to open drop-down menu.
4. Notice the “Display statistics” menu option is in English.
5. Click on the “Translate” button to initiate the translation process.
6. Notice that the messages displayed on the infobar, such as “Loading translation engine…”, “Automatic Translation enabled.”, etc are in English.

Actual:
The infobar is not completely localized in BG.

Expected:
The entire infobar should be localized in the browser locale language.

NOTE:
I will update this bug with similar findings when I manage to test other browser locales as well, as it’s most likely the issue occurs for other browser locales too. 

![2022-03-10_12h23_11](https://user-images.githubusercontent.com/50236075/157645243-7650c18b-54fb-44fe-90c7-23435b73ddc3.png)

![2022-03-10_12h23_45](https://user-images.githubusercontent.com/50236075/157645309-9ef70bc8-b5b0-4a5e-82df-821b104f28eb.png)

**Comment by andrenatal** [comment] 2022-03-10 12:50
This is not actually an issue but a by design expected behavior. The extension is being localized on pontoon [1], and when a string's translation is not available, it will default to English. T

here's also some translations on Firefox' default dtd, so that's why even Bulgarian is empty on pontoon, some label will be localized. 

Will close this.

cc @flodolo 

[1] https://pontoon.mozilla.org/projects/firefox-translations-add-on/

**Closed by andrenatal** 2022-03-10 12:50 UTC
