### ISSUE TITLE
Feature to show original text should not reload the page

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/firefox-translations#587] opened 2022-11-26 14:36 UTC
After translation a new button in Firefox Translations 1.2.0 allows to show the original content. In fact it just reloads the page. Similar to TranslateLocally Firefox Translations should allow to show the original content without reloading the page.

**Comment by andrenatal** [comment] 2022-12-03 04:31
duplicate of #327

**Closed by andrenatal** 2022-12-03 04:31 UTC
Labels: needs triage
