### ISSUE TITLE
Needs right click context menu listing

### ISSUE THREAD

**Issue by jkemp814** [mozilla/firefox-translations#578] opened 2022-11-19 20:35 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to copy and paste into the free-form. No balloon popup after highlighting text to copy.

**Describe the solution you'd like**

There needs to be a way to translate copied text in a webpage by either having a popup balloon or copy text and it autopopulate the free-form area or selecting from the right-click context menu. If highlighted text is copied, the user has to open the free-form section and paste. Would be nice to have it, once copied, paste into free-form section automatically and detect language.  

The add-on page reviews are a perfect example. There are many reviews in other languages, some not recognizable, so it's hard to determine which source language to choose. 

**Describe alternatives you've considered**

Manually copy text and paste in free-form, guess source language

**Additional context**

Free-form needs to automatically detect source language when text is pasted into 'source language' field. 

Other issues mentioning similar requests:
#358 #568 #572

**Comment by andrenatal** [comment] 2022-12-03 04:26
duplicate of #358

**Closed by andrenatal** 2022-12-03 04:26 UTC
Labels: enhancement, UI/UX
