### ISSUE TITLE
Option to stop translation and show original text

### ISSUE THREAD

**Issue by Yona-TYT** [mozilla/firefox-translations#467] opened 2022-07-26 15:01 UTC
Currently I have problems posting on twitter when I activate the translator, because I needed to write in English but the plug-in translates everything I write into Spanish.

A button to stop the translation of the site momentarily while I write a post, that would be nice and very useful.

Greetings and thank you very much for this great plugin. :)

**Comment by andrenatal** [comment] 2022-07-26 18:09
Hi @Yona-TYT , you can switch off the option `Enable translation of forms`

**Comment by Yona-TYT** [comment] 2022-07-26 18:19
@andrenatal 
The "Enable translation of forms" option doesn't seem to be available on the twitter page for some reason.

Here on github if it appears

**Comment by Yona-TYT** [comment] 2022-07-26 18:28
[Grabación de pantalla desde 26-07-22 14:23:18.webm](https://user-images.githubusercontent.com/27737574/181083446-505422bc-1679-4d9f-9910-8389f5d8da13.webm)

I have also noticed that it is impossible to write on twitter while the translation is activated, see the attached video.

**Comment by Yona-TYT** [comment] 2022-07-27 16:16
I should also mention that typing is impossible, because the typing bar moves to the left constantly when translation is on.

**Comment by andrenatal** [comment] 2022-07-28 06:33
Yes, that's a real issue that I can reproduce. Problem is that the input field on twitter is actually a `span` element, which the parser thinks it's actually a translatable element.

**Comment by jelmervdl** [comment] 2022-07-28 11:54
For some reason I forgot to exclude all elements with contenteditable attributes? I've added exclusions for them in #476 which for me fixed Twitter. With that change you should be able to compose tweets without the browser fighting you.

Note that Twitter still looks a bit weird where not all tweets are always translated. That's because Twitter does its own language identification on tweets and adds `lang` attributes for each of them. If their language identification fails, and it did not match the source language the add-on expected, it will not translate the tweet. And for me their language identification fails quite often for shorter tweets, identifying English tweets as Romanian etc.

**Comment by Yona-TYT** [comment] 2022-07-28 12:11
@jelmervdl 
Thank you very much!, I will try it as soon as it is available.

By the way, currently every time I want to go back to the original text on any page I am forced to reload the page, is there a way to display the original text without reloading the page?, or maybe this hasn't been implemented yet?.

**Comment by jelmervdl** [comment] 2022-07-28 12:14
It hasn't been implemented yet.

I'm working on an initial implementation, but I'm expecting some trouble, especially with sites like Twitter that have dynamic content, or content changes that happened after the translation was inserted. For those pages, just reverting the state of the page to before the translation isn't going to be sufficient I expect.

**Comment by andrenatal** [comment] 2022-07-28 17:15
I'll land the fix to contenteditable that will close this issue, but the request to show original text will be tracked here: https://github.com/mozilla/firefox-translations/issues/404

**Comment by andrenatal** [comment] 2022-07-28 21:12
fixed by #478

**Closed by andrenatal** 2022-07-28 21:12 UTC
Labels: bug, page-parser
