### ISSUE TITLE
Error when attempting to translate We found an error loading the translation engine

### ISSUE THREAD

**Issue by fluffynuts** [mozilla/firefox-translations#424] opened 2022-06-28 11:54 UTC
**Describe the bug**
I tried to translate https://github.com/kodemaker/kodemaker.no. Firefox Translations suggests this page is in Norwegian:
![image](https://user-images.githubusercontent.com/4669340/176171602-315730c0-5749-45f6-834d-f6b54b48efd9.png)

and when I click translate:
![image](https://user-images.githubusercontent.com/4669340/176171680-55772574-5fc4-44a9-b615-291bcf868cbc.png)

**To Reproduce**
1. Go to 'https://github.com/kodemaker/kodemaker.no'
2. Click on 'Translate`
3. Be sad

**Expected behavior**
I expected translation. I've used the extension before when it was in beta and it worked fairly well.

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 104.0a1 (2022-06-27)
- Processor information: intel i9 12900
- OS version: Windows 11
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: https://github.com/kodemaker/kodemaker.no
- Language of the webpage: Firefox Translations claims Norwegian. I wouldn't know 😂 
- Translating to (language): English
- Console logs from Web Developer Tools:
```
Using optimized gemm (mozIntGemm) implementation 2 [bergamot-translator-worker.js:2952:17](moz-extension://e8027946-a5c7-4182-add0-a9cc3fc87f3e/controller/translation/bergamot-translator-worker.js)
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.003 secs 2 [translationWorker.js:75:29](moz-extension://e8027946-a5c7-4182-add0-a9cc3fc87f3e/controller/translation/translationWorker.js)
​```

**Comment by fluffynuts** [comment] 2022-07-01 04:46
I did. I think that's the default? Or at least that the add-on is remembering me clicking it.

**Comment by andrenatal** [comment] 2022-07-05 20:08
Thanks. This is a duplicate of https://github.com/mozilla/firefox-translations/issues/384 then. It will be fixed in the upcoming release.

**Closed by andrenatal** 2022-07-05 20:08 UTC
Labels: can't reproduce, needinfo
