### ISSUE TITLE
Add Original Text popup and selection features & assign shortcuts to it.

### ISSUE THREAD

**Issue by minshifu** [mozilla/firefox-translations#516] opened 2022-10-04 09:23 UTC
Thank you first for this long overdue function. I have been waiting for built-in translation for firefox for years and am surprised and excited to find it finally came out. I have 2 little suggestions which I think can help improve on the addon. Pls kindly consider them.

1) Could you pls enable original text popup and selection on mouseover. These features will make the comparison between translation and original texts easier. And the utilization of both translation and original texts will also become more convenient.

2) Pls also kindly assign a shortcut to toggle between translation and original versions on webpages. This will also make the addon more user-friendly.

   Thanks a lot and best regards!

**Comment by andrenatal** [comment] 2022-11-02 23:00
Dupe of #327. Let's track it there. Thanks @minshifu !

**Closed by andrenatal** 2022-11-02 23:00 UTC
Labels: enhancement
