### ISSUE TITLE
support Android

### ISSUE THREAD

**Issue by zez3** [mozilla/firefox-translations#379] opened 2022-06-05 17:36 UTC
Would be nice to gave this in Android. Not sure what for an impact would have on battery 🔋😩 or if it's even feasible

**Comment by cadeyrn** [comment] 2022-06-05 20:33
Duplicate of #374.

**Comment by andrenatal** [comment] 2022-06-07 18:59
Closing since it's a duplicate as noted above.

**Closed by andrenatal** 2022-06-07 18:59 UTC
