### ISSUE TITLE
Languages in which pages should never be translated are not automatically selected in the language drop-down list in the translation bar.

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/firefox-translations#474] opened 2022-07-27 21:43 UTC
Autoselect language in the “choose language” DropDown of the translation bar.

The language may be autodetected according to the content text or simply by reading the page html tag lang attribute.

**Comment by andrenatal** [comment] 2022-07-28 06:27
Hi @SuperPat45 . This is actually the intended behavior. Could you please share the steps to reproduce the issue you are having?

**Comment by SuperPat45** [comment] 2022-07-28 09:41
My browser is in French, but I need to select language myself for each English pages :
![image](https://user-images.githubusercontent.com/7791600/181474166-3c18c759-c196-4386-abaa-e14bc57a89d6.png)

**Comment by andrenatal** [comment] 2022-12-13 04:03
@SuperPat45 are you still seeing this error?

**Comment by SuperPat45** [comment] 2022-12-13 10:35
I still have this issue but I discover it is because I set to never translate pages in english to not have the bar pop up automatically. So, when I open the translation bar with the address bar button, english is still not selected for english pages.

**Comment by marco-c** [comment] 2023-07-11 12:57
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
This problem is fixed in the built-in version.

**Closed by marco-c** 2023-07-11 12:57 UTC
Labels: enhancement, language detection
