### ISSUE TITLE
Add an option to redo translation

### ISSUE THREAD

**Issue by kpatenio** [mozilla/firefox-translations#341] opened 2022-05-20 22:29 UTC
Sometimes, not all parts of a page are translated until I refresh the page and re-run the translation. I think it would be interesting to see an option to redo a translation from the extension infobar without having to rely on a full refresh.

**Comment by andrenatal** [comment] 2022-05-20 22:38
Hi @kpatenio . Could you please share the STR with screenshots and specially the URLs where you are seeing this behavior, please? 

Thanks!

**Comment by kpatenio** [comment] 2022-05-25 16:20
Hi, sorry for the delayed response. I originally encountered the issue in https://www.amazon.es/ while testing Spanish, but unfortunately I lost the link that I used and am having a hard time reproducing it there (it seems to be intermittent, depending on the product page loaded). I am somewhat able to reproduce something similar on another site, but I have a feeling there's another issue involved.

STR:

1. Go to https://www.moulinex.es/
2. Click the addon icon on the toolbar
3. Enable Spanish translation
4. Enable "Turn on automatic translation as you browser in this tab"
5. Notice that page is translated into English
6. Go down to footer and select `Choose your Companion` (`Elige tu Companion`, or this [URL](https://www.moulinex.es/companion-guia-de-compra))

![Screen Shot 2022-05-25 at 08 55 20](https://user-images.githubusercontent.com/25045015/170308385-d9768509-aa03-4955-9cfa-1567bdb5bab1.png)
(Ignore untranslated Spanish in screenshot above - this is just to show which footer link I chose)

7. New page will load, but this time Spanish is not translated or is partially translated

As a user, I would expect to have the ability to re-translate in case something like this happens. If refreshing the page is really needed, I wish there was a prompt on the addon info bar saying so, just to make it more obvious.

I found additional buggy behaviour (a new issue?) with the following steps: 

8. Reload page and notice that the same page (Choose your Companion) might not be fully translated into English
9. Click addon icon on the toolbar
10. Notice that Translate option is either missing or nothing happens after pressing Translate button for Spanish (text remains untranslated)
![Screen Shot 2022-05-25 at 08 56 07](https://user-images.githubusercontent.com/25045015/170308404-48bfcf47-9765-4eff-89e7-f7c28568c2f2.png)

This was tested on MacOS Big Sur 11.6 and Firefox Nightly version 102.0a1 (2022-05-24).

**Comment by andrenatal** [comment] 2022-06-07 18:05
Hi @kpatenio, we are aware of issues where some parts of pages aren't being translated, but I couldn't reproduce this one. Could you please test with the version being currently distributed on https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ and see if you are still seeing this behavior? We applied a large number of fixes since when you originally posted this issue.

**Comment by kpatenio** [comment] 2022-06-07 20:51
Hi @andrenatal - I can no longer reproduce the issue. Thanks for the follow up!

**Comment by andrenatal** [comment] 2022-06-07 21:03
Thanks @kpatenio! Will close this then.

**Closed by andrenatal** 2022-06-07 21:03 UTC
Labels: can't reproduce, needinfo
