### ISSUE TITLE
Translation engine downloading progress not very informative, especially with a slower network

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/firefox-translations#329] opened 2022-05-12 07:39 UTC
In my office network, it took quite some time to finish downloading the translation engine, see the attached screenshot.

After the first time I click the "Translate" button, it feels like nothing is happening and takes me some time to notice this progress text. There're long intervals between each of its update, and when it does update, I'm always seeing the same numbers before and after "of", which doesn't really help in understanding the progress.

I suspect this wouldn't be so confusing on a faster network.

![translation-download-progress](https://user-images.githubusercontent.com/31391/168014895-1746e08f-489a-470f-adec-177eea95937c.png)

**Comment by andrenatal** [comment] 2022-05-20 22:41
Hi @l-hedgehog on the upcoming 1.1.2 version this might have been sorted (i.e. the download progress is more responsive). Please let us know if that version has this issue addressed for you.

Thanks!

**Comment by l-hedgehog** [comment] 2022-05-31 03:05
Hi @andrenatal

I tested 1.1.2 and the progress text is definitely updated more frequently. Thanks!

However, at least initially, there seems to be two simultaneous downloads, and the text was updated like this:
"a1 of A" => "b1 of B" => "a2 of A" => "b2 of B" => ...
Which may not be ideal.

**Comment by andrenatal** [comment] 2022-11-04 07:48
Hi @l-hedgehog , we are going to replace that UI in a future version, but since your original issue was fixed, I'm going to close this since that's the by design behavior.

**Closed by andrenatal** 2022-11-04 07:48 UTC
Labels: enhancement, UI/UX
