### ISSUE TITLE
Form translation dialogues hidden behind page's modal veil

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations#12] opened 2021-11-29 12:58 UTC
On booking.com when trying to use "Form translation", two text fields appear behind the grey overlay that booking.com uses to give the impression of a modal dialogue.  
![bottom](https://user-images.githubusercontent.com/247512/143871417-4622f414-3469-46a1-815e-9579bcce1729.png)

0. Install current extension
1. https://www.booking.com/hotel/gb/park-plaza-westminster-bridge.es.html
2. Click translate
3. Click Yes to enable translations of forms (and wait an unusually long time for "Loading form translation")
4. Click "Ask a question." lower down in the page to open a modal dialogue.  
5. Click on the textarea.

**Comment by andrenatal** [comment] 2022-01-23 09:23
Dupe of #16

**Closed by andrenatal** 2022-01-23 09:23 UTC
